
#include "driver/gpio.h"

#define CURRENT_SENSE_A GPIO_NUM_6
#define CURRENT_SENSE_B GPIO_NUM_5
#define CURRENT_SENSE_C GPIO_NUM_4

#define MOTOR_HIGH_A GPIO_NUM_42
#define MOTOR_HIGH_B GPIO_NUM_41
#define MOTOR_HIGH_C GPIO_NUM_40

#define ETHERNET_INT_0 GPIO_NUM_16
#define ETHERNET_INT_1 GPIO_NUM_7
#define CHIP_SELECT_W5500_0 GPIO_NUM_17
#define CHIP_SELECT_W5500_1 GPIO_NUM_15

#define CHIP_SELECT_SD GPIO_NUM_10
#define CHIP_SELECT_ENCODER GPIO_NUM_13
#define CHIP_SELECT_MOTOR_DRIVER GPIO_NUM_48

#define SPI_MISO_0 GPIO_NUM_21
#define SPI_MOSI_0 GPIO_NUM_47
#define SPI_CLK_0 GPIO_NUM_14

#define SPI_MISO_1 GPIO_NUM_18
#define SPI_MOSI_1 GPIO_NUM_9
#define SPI_CLK_1 GPIO_NUM_8

#define I2C_SDA GPIO_NUM_11
#define I2C_SCL GPIO_NUM_12

#define IMU_INT1 GPIO_NUM_39
#define IMU_INT2 GPIO_NUM_38

#define IO_EXPANDER_LED0 0
#define IO_EXPANDER_LED1 1
#define IO_EXPANDER_LED2 2
#define IO_EXPANDER_DIP_SWITCH_0 3
#define IO_EXPANDER_DIP_SWITCH_1 4
#define IO_EXPANDER_MOTOR_LOW_C 5
#define IO_EXPANDER_MOTOR_LOW_B 6
#define IO_EXPANDER_MOTOR_LOW_A 7
#define IO_EXPANDER_INA_ALERT 8
#define IO_EXPANDER_SD_CARD_DETECT 9
#define IO_EXPANDER_MOTOR_FAULT 10
#define IO_EXPANDER_MOTOR_ENABLE 11
#define IO_EXPANDER_MOTOR_CALIBRATION 12
#define IO_EXPANDER_ETHERNET_RESET_0 13
#define IO_EXPANDER_ETHERNET_RESET_1 14
#define IO_EXPANDER_TEMP_OS 15
